#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=1
	
	# Test because file doesn’t exist at first install. It is created at first page opening.
	if test -f "$install_dir/inc/digiwords.db"
	then
		# Create a temporary directory
		tmpdir="$(mktemp -d)"
	
		# Backup the inc/digiwords.db file to the temp dir
		cp -ar "$install_dir/inc/digiwords.db" "$tmpdir/digiwords.db"
	
		# Download, check integrity, uncompress and patch the source from app.src
		ynh_setup_source --dest_dir="$install_dir" --full_replace=1
	
		# Copy digiwords.db back to the install_dir
		cp -ar "$tmpdir/digiwords.db" "$install_dir/inc/digiwords.db"

		# Remove the tmp directory securely
		ynh_secure_remove --file="$tmpdir"
	else
		# Download, check integrity, uncompress and patch the source from app.src
		ynh_setup_source --dest_dir="$install_dir" --full_replace=1
	fi
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
 